### ISSUE TITLE
css-tree updated - breaks react-native-svg

### ISSUE THREAD

**Issue by andrewrt** [react-native-svg/react-native-svg#1482] opened 2020-10-27 19:28 UTC
# Bug

In the current react-native-svg - the css-tree dep was just updated from 1.0.0.alpha39 to 1.0.0, and they removed HexColor in place of Hash.js

#### Unexpected behavior

Error saying 
Unable to resolve module './HexColor' from node_modules/css-tree/lib/syntax/node/index.js

## Environment info

Library version: 
```json
 "react-native-svg": "^12.1.0",
```

## Steps To Reproduce

Do a clean RN app install w/ react-native-svg without specifying css-tree. 

Describe what you expected to happen:

1. No crashes in the simulator

## Workaround

Current workaround / fix is to specify css-tree exact in package.json:
```sh
npm i css-tree@v1.0.0-alpha.39 --save-exact
```

**Comment by kicketster** [comment] 2020-10-28 14:29
See this issue today. Is there any long term fix?

**Comment by cjpatoilo** [comment] 2020-10-29 02:50
Here I had the same error. 
Now worked fine after run `$ npm i css-tree@v1.0.0-alpha.39 --save-exact`. 

Thank you @andrewrt 🙏

**Comment by andrewrt** [comment] 2020-10-29 14:15
> point

css-tree@v1.0.0-alpha.39 is the most recent that functions with react-native-svg currently. 
To make react native svg work w/ yesterday's css-tree release, will need a pull request to update links from HexColor.js to Hash.js

**Comment by andrewrt** [comment] 2020-10-29 14:24
to point back to the most recent @kicketster , npm uninstall css-tree ... (and probably uninstall/reinstall react-native-svg. )

**Comment by enestatli** [comment] 2020-11-01 10:04
`unable to resolve module ./hexcolor from node_modules\css-tree\lib`

I kept getting this error while fresh building, thanks to @andrewrt workaround, it's solved. Thank you.

**Comment by bluenex** [comment] 2020-11-04 08:21
I have checked and found that `react-native-svg` doesn't call `HexColor` at all.

https://github.com/react-native-svg/react-native-svg/blob/b2e2c355204ff4b10973d3afce1495f7e4167ff7/src/css.tsx#L17-L29

Thus I think the problem is about node modules caching, so I try closing the metro bundler and open the new one resetting the cache:

```sh
npx react-native start --reset-cache
```

This solves the error on build for me.

**Comment by kdfemi** [comment] 2020-11-13 04:40
> I have checked and found that `react-native-svg` doesn't call `HexColor` at all.
> 
> https://github.com/react-native-svg/react-native-svg/blob/b2e2c355204ff4b10973d3afce1495f7e4167ff7/src/css.tsx#L17-L29
> 
> Thus I think the problem is about node modules caching, so I try closing the metro bundler and open the new one resetting the cache:
> 
> ```shell
> npx react-native start --reset-cache
> ```
> 
> This solves the error on build for me.

This also worked for me

**Comment by SnaiNeR** [comment] 2020-11-18 17:00
npm start -- --reset-cache also helped!
issue appeared after upadting RN and correspond libraries

**Comment by WoLewicki** [comment] 2022-02-24 13:29
As it seems like a problem with cache and not with the library, I will close it then. Feel free to comment here if I am wrong and we can reopen it then.

**Closed by WoLewicki** 2022-02-24 13:29 UTC
