### ISSUE TITLE
svg blinks on navigation

### ISSUE THREAD

**Issue by jrafaaael** [react-native-svg/react-native-svg#1830] opened 2022-08-09 19:55 UTC
NB Never post screenshots of code. Post copy paste-able code if you include any.
Ignoring this will likely lead to direct closing of the issue.
Please respect the time and energy of open source maintainers.

# Bug

I'm usign `react-native-svg` and `react-navigation` (`@react-navigation/native`, `react-native-screens`, `react-native-safe-area-context` and `@react-navigation/native-stack`). When I go (with `navigation.navigate(...)`) from one screen to another screen, the svg placed on it blinks.

## Environment info

```json
    "@react-navigation/native": "^6.0.11",
    "@react-navigation/native-stack": "^6.7.0",
    "expo": "~45.0.0",
    "expo-status-bar": "~1.3.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.2",
    "react-native-safe-area-context": "4.2.4",
    "react-native-screens": "~3.11.1",
    "react-native-web": "0.17.7",
    "react-native-svg": "12.3.0"
```

## Steps To Reproduce

Issues without reproduction steps or code are likely to stall.

1. git clone https://github.com/jrafaaael/rn-expo-navigation-svg-bug
2. cd rn-expo-navigation-svg-bug
3. npm install
4. npm run start

Describe what you expected to happen:

1. The svgs should never blink when you go to another screen

## Short, Self Contained, Correct (Compilable), Example

If you are having a problem with some code and seeking help, preparing a Short, Self Contained, Correct Example (SSCCE) is very useful. But what is an SSCCE?

It is all in the name, really. Take a look at each part. The version prepared for others to see should be:

Short (Small) - Minimise bandwidth for the example, do not bore the audience.
Self Contained - Ensure everything is included, ready to go.
Correct - Copy, paste, (compile,) see is the aim.
Example - Displays the problem we are trying to solve.

http://www.sscce.org/

**Comment by WoLewicki** [comment] 2022-08-10 10:45
I think it is a duplicate of the behavior mentioned in linked issues here: https://github.com/react-native-svg/react-native-svg/pull/1542 so I will close it. Feel free to comment here if I am wrong and we can always reopen it.

**Closed by WoLewicki** 2022-08-10 10:45 UTC
