### ISSUE TITLE
Unimplemented component: <RNSVGView> 

### ISSUE THREAD

**Issue by chonghow97** [react-native-svg/react-native-svg#1731] opened 2022-03-26 18:24 UTC
# Bug
### React Native version: 0.68.0-rc.1
with fabric 

```tsx
import Svg, {Circle, Rect} from 'react-native-svg';
return(
<Svg height="50%" width="50%" viewBox="0 0 100 100">
          <Circle
            cx="50"
            cy="50"
            r="45"
            stroke="blue"
            strokeWidth="2.5"
            fill="green"
          />
          <Rect
            x="15"
            y="15"
            width="70"
            height="70"
            stroke="red"
            strokeWidth="2"
            fill="yellow"
          />
        </Svg>
)
```
<img width="335" alt="image" src="https://user-images.githubusercontent.com/31228115/160252215-38900b98-a7a4-4c16-ba7f-960a3d2cf9f4.png">

## Environment info

Run `react-native info` in your terminal and copy the results here. Also, include the *precise* version number of this library that you are using in the project

React native info output:

```bash
System:
    OS: macOS 12.3
    CPU: (8) arm64 Apple M1
    Memory: 93.06 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.0-rc.1 => 0.68.0-rc.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: ^12.3.0

## Steps To Reproduce

Issues without reproduction steps or code are likely to stall.

3. yarn
4. cd ios
5. RCT_NEW_ARCH_ENABLED=1 pod install
6. yarn ios
7. yarn android
8. ...

Describe what you expected to happen:

1. all svg show as expected

http://www.sscce.org/

**Comment by WoLewicki** [comment] 2022-04-13 09:45
You will get `Unimplemented component` view for all components that are not migrated to Fabric yet, so almost every lib right now. Since `react-native-svg` does not support Fabric yet (we are working on it), you shouldn't use `RCT_NEW_ARCH_ENABLED=1` in apps with it. Can I help you more with this?

**Comment by NathHorrigan** [comment] 2022-04-18 13:55
Hi @WoLewicki - Is there an estimate on how long fabric support should take to land?

**Comment by WoLewicki** [comment] 2022-04-19 10:03
@NathHorrigan I don't want to provide any exact dates etc since there are too many potential problems that may occur during adding the Fabric support. I will probably open a draft PR where you will be able to track the current progress of the process. Since it is not a bug, I will close this issue. Feel free to comment here if you think it should be opened and we can always reopen it then.

**Closed by WoLewicki** 2022-04-19 10:03 UTC

**Comment by KMJ-007** [comment] 2024-12-03 08:37
any update on this?

**Comment by jakex7** [comment] 2024-12-03 10:17
@KMJ-007 The `react-native-svg` library now has full support for Fabric, so there shouldn't be any issues with it.

**Comment by KMJ-007** [comment] 2024-12-03 10:35
yeah, thankyou 

just need to rebuild the app
