### ISSUE TITLE
SvgUri On Error

### ISSUE THREAD

**Issue by prashantchothani** [react-native-svg/react-native-svg#1105] opened 2019-09-13 07:15 UTC
# Feature Request

 We need to have an on Error when we use svgUri as the app crashes if there is an error in the SVG format. A best practice guide on the format of the svg from uri is also required as it is based on trial and error and standard svg's do not load and app crashes

## Why it is needed

  In case the svg's are coming from a third party source and if the svg is not confirming to the specs required by react-native-svg, the app crashes. This can be handled and a default svg can be shown.

## Possible implementation

  It really helps if you could describe from a technical POV how this new feature would work, which code it rely on, etc

### Code sample

  Please show how the new code could work, if doable

**Comment by msand** [comment] 2019-09-28 12:11
Would you be available to work on this? Could you make a pr?

**Comment by prashantchothani** [comment] 2019-09-30 05:12
SvgUri loads svg from a url. We could have a onError prop which could be used to show a default svg image from local images. We noticed that in case of any missing svg's or not well formattted svg's from third party the whole application crashes. To avoid this, it would be helpful. Also the svg loads on component did mount of the view where we use svgURI and we could not trap the error as it happens inside the SvgUri library

**Comment by YuriiStetsula** [comment] 2019-10-07 16:38
@prashantchothani  as a workaround you can implement something like this https://gist.github.com/YuriiStetsula/ccac4e5920db289bcbbd3c029096e3e6

**Comment by uqmessias** [comment] 2020-01-27 19:19
@msand and @prashantchothani, has anyone worked on this?
I'd be glad to work on this issue. In fact, I'v been working on a `react-native-svg-uri` fork called [`react-native-svg-renderer`](https://github.com/uqmessias/react-native-svg-renderer) for a while and this was implemented there. But I just realized, today, that `SvgUri` and `SvgXml` is already implemented here (starting from v7.0.0).

So, if anyone has taken this feature request yet, I'd be glad to work on it.

**Comment by uqmessias** [comment] 2020-01-28 17:16
@prashantchothani,
I just submitted a PR with the changes.

@msand, I couldn't find the `example/App.js` file. Is it on a different repository?

**Comment by prashantchothani** [comment] 2020-01-29 06:10
@uqmessias @msand  appreciate your taking up this issue. it would be nice to have an onError prop as mentioned above.

**Comment by msand** [comment] 2020-01-31 17:55
@uqmessias Thanks for working on this, will take a closer look at it and test it tomorrow. There's no example file in this repo, there are some in https://github.com/msand/react-native-svg-e2e  
There's also another example repo in https://github.com/react-native-community/react-native-svg#run-example / https://github.com/magicismight/react-native-svg-example.git but that hasn't been maintained for quite some time, instead I've kept it functional here: https://snack.expo.io/@msand/react-native-svg-example

**Comment by msand** [comment] 2020-01-31 17:55
The pr template comes from react-native-community rather than from this repo. Should probably make a repo specific one instead.

**Comment by uqmessias** [comment] 2020-01-31 22:14
@msand, what do you think about getting the example app and adding it to this repo? This way, we can keep it updated.

**Comment by msand** [comment] 2020-03-08 10:17
I've made the e2e app work again, might make sense to move it here yeah, mind making a pr for it?

**Comment by uqmessias** [comment] 2020-03-08 17:46
@msand,
This week I'm really busy, but if I can't find some time to do that in the next days, I'll in the next week.

**Comment by UserSina** [comment] 2020-03-29 16:51
Any news about this topic ?

**Comment by uqmessias** [comment] 2020-03-29 23:18
I couldn't find any time to do that yet. But I'm planning to do during this week.

**Comment by JacobBarr1986** [comment] 2020-08-18 10:35
Any news about this topic ?

**Comment by uqmessias** [comment] 2020-09-09 15:52
@JacobBarr1986, it was merged in the #1266

**Comment by prashantchothani** [comment] 2020-09-14 10:18
@uqmessias Thanks for this effort and I tried to use the onError Prop to pass a SVG Component to load that in case of error of the SVG URI. But still it crashes. Any help on how can i use this prop and gracefully show a default image ?

**Comment by prashantchothani** [comment] 2020-09-21 09:27
Any news please ?

**Comment by uqmessias** [comment] 2020-09-23 22:59
Hey @prashantchothani, how are you doing? I hope you're well 😄 

You can use the `onError` callback to show another view instead of the SVG with error, to do that, we may need to use something to hold the state of this SVG, in the following example, I'll use `useState` hook, but you can solve the same problem with other solutions:

```jsx
const MySVG = () => {
  const [hasError, setError] = useState(false);
  const handleError = useCallback(() => {
    setError(true);
  }, []);

  if (hasError){
    return (
      <Text>There's an error in the SVG file</Text>
    );
  }

  return (
    <SvgXml
        xml='<svg width="400" height="180">\n<rectwitherror x="50" y="20" width="150" height="150" style="fill:blue;stroke:pink;stroke-width:5;opacity:0.5" /></svg>'
        onError={handleError}
    />
  );
}
```

**Comment by vinitgundeti** [comment] 2020-09-24 09:51
hi @uqmessias i have used above solution for SvgUri but onError app is crashing

this is my code

`export default React.memo(function Segment(props) {
    const [hasError, setError] = useState(false);
    const handleError =()=>{
        setError(true)
    }
  return(
         <View>
               {hasError ?
                    <Text>error</Text>
                    :
                    <SvgUri
                        width={22}
                        height={22}
                        uri={Urls.svgAirlineImageUrl + data.vc + ".svg"}
                        onError={handleError}
                    >
                    </SvgUri>
                }
            </View>
)})
`

i get this error when i pass wrong svg
![Screenshot 2020-09-24 at 3 20 56 PM](https://user-images.githubusercontent.com/47896506/94129873-8c813f80-fe79-11ea-95f5-5cf09cbee8fa.png)

can you please help where i am doing wrong

**Comment by prashantchothani** [comment] 2020-09-24 11:30
@uqmessias I am fine and hope all's well with you and your family :)

Even i got the same issue.

**Comment by uqmessias** [comment] 2020-09-24 14:18
Hey @prashantchothani and  @vinitgundeti, does it work if you change your example to the following?

```diff
diff --git a/your-example.jsx b/your-example.jsx
index 392360b31..ece36f1bc 100644
--- a/your-example.jsx
+++ b/your-example.jsx
@@ -13,8 +13,7 @@ export default React.memo(function Segment(props) {
                         height={22}
                         uri={Urls.svgAirlineImageUrl + data.vc + ".svg"}
                         onError={handleError}
-                    >
-                    </SvgUri>
+                    />
                 }
             </View>
 )})
```

**Comment by vinitgundeti** [comment] 2020-09-25 14:35
Hi @uqmessias it's not working even i change it like above

**Comment by uqmessias** [comment] 2020-09-25 17:04
@vinitgundeti, are you getting any new error or something? Because the previous error was regarding to the missing `children` value (default to `null`)

**Comment by vinitgundeti** [comment] 2020-09-28 05:07
@uqmessias i am getting the same error

![Uploading simulator_screenshot_1083F706-999C-49E4-8F5B-E82A3FBFCFC1.png…]()

**Comment by uqmessias** [comment] 2020-10-06 14:07
Hey @vinitgundeti, sorry for taking so long to answer!

Can you upload a sample code to Github and send the link so I can test it and try to help you with that?
I'm not actively working with React Native currently (working with other technologies and other projects) and if you could send me this sample it would be a lot easier to spot the error and I probably could you faster.

**Comment by vinitgundeti** [comment] 2020-10-15 10:02
Hey @uqmessias, sorry for late reply

this is my git repo link
https://github.com/vinitgundeti/reactnativesvg.git 

i have made component svgcomponent.js added it in App.js

in code i have added wrong svg link the right link i have mentioned in readme

**Comment by uqmessias** [comment] 2020-10-16 17:54
@vinitgundeti, this is an issue on the initial implementation of `onError`, I just opened a PR to fix that:
https://github.com/react-native-svg/react-native-svg/pull/1476

@msand, can you take a look at it, pls?

**Comment by vinitgundeti** [comment] 2020-10-23 07:10
@uqmessias is this merged in release ?

**Comment by vinitgundeti** [comment] 2020-10-23 07:22
@uqmessias Thank you very much for fixing this, this was must required feature, i have tested it and it is working fine. when will this be in the main branch ?

**Comment by staghouse** [comment] 2020-11-18 08:47
Just wanted to throw my hat in the ring and say this would be great to be fixed,

**Comment by GeorgeAverkin** [comment] 2020-12-31 08:42
As a workaround, it possible to prevent app from crashing using [error boundaries](https://reactjs.org/docs/error-boundaries.html).
`
<ErrorBoundary>
<SvgXml
        xml='...'
    />
</ErrorBoundary>
`

**Comment by alemarra89** [comment] 2021-02-02 14:23
Hi all, I don't know how many of you are using the onError props, but I think we have to update ts definitions in order to make is available in typescript.

in src/index.d.ts, this code

`export interface SvgProps extends GProps, ReactNative.ViewProperties {
  width?: NumberProp;
  height?: NumberProp;
  viewBox?: string;
  preserveAspectRatio?: string;
  color?: Color;
  title?: string;
}`

probably should become

`export type AdditionalProps = {
  onError?: (error: Error) => void;
  override?: Object;
};

export interface SvgProps extends AdditionalProps, GProps, ReactNative.ViewProperties {
  width?: NumberProp;
  height?: NumberProp;
  viewBox?: string;
  preserveAspectRatio?: string;
  color?: Color;
  title?: string;
}
`

**Comment by Khuongnb** [comment] 2021-11-27 05:08
:))) Same issue brought me here, took me several hours to find out which uri is dead in hundreds of them

**Comment by SamuelLin** [comment] 2021-12-17 05:42
I think it still crash the app when remote url is failed

**Comment by ian** [comment] 2022-01-30 14:15
Dealing with same issue. A bad SVG will crash the entire server, and this library doesn't seem to play nice with error boundaries.

**Comment by WoLewicki** [comment] 2022-04-19 09:56
Hey, since https://github.com/react-native-svg/react-native-svg/pull/1503 and https://github.com/react-native-svg/react-native-svg/pull/1718 have been merged, do you think we can close it? It would be nice if you could test it and see if there are some scenarios that are not yet handled though.

**Comment by WoLewicki** [comment] 2022-05-26 13:33
@gabimoncha are you sure you updated the library version? And if so, could you post a small reproduction of the problem with a short description of what is the issue exactly?

**Comment by lorran-xo** [comment] 2022-06-10 12:09
My project has the current version (12.3.0) and onError still not working properly, even using [this example](https://github.com/react-native-svg/react-native-svg#error-handling).

It throws me this error:

![image](https://user-images.githubusercontent.com/58430075/173061302-5ec1618d-b943-42be-900c-3677abf0c92e.png)

**Comment by igorcesarcode** [comment] 2022-06-26 01:44
I have the same problem as @lorran-xo

**Comment by NNVuGiao** [comment] 2022-06-28 10:20
I'm having this issue, app crash when the url of svg file return error 404.
I hope it can just render null instead of crashing. It is not ideal for production.

**Comment by WoLewicki** [comment] 2022-07-26 11:33
I could not reproduce the problem in newest versions. I will close this issue then. Feel free to comment here with a repo with reproduction and we can always reopen it then.

**Closed by WoLewicki** 2022-07-26 11:33 UTC
Labels: enhancement, help wanted, good first issue

**Comment by mahmoud595** [comment] 2023-02-01 21:26
<img width="366" alt="Screenshot 2023-02-01 at 11 20 43 PM" src="https://user-images.githubusercontent.com/56139198/216166243-4ca6da36-3d8d-4726-b0b2-65b13c85ee9d.png">

onError still doesnot catch error if the svg cannot be parsed.

react-native-svg : 13.6.0
react-native: 0.70.6

**Comment by mahmoud595** [comment] 2023-02-01 21:55
`export function SvgUri(props: UriProps) {
  const { onError = err, uri, onLoad } = props;
  const [xml, setXml] = useState<string | null>(null);
  useEffect(() => {
    uri
      ? fetchText(uri)
          .then((data) => {
            setXml(data);
            onLoad?.();
          })
          .catch(onError)
      : setXml(null);
  }, [onError, uri, onLoad]);
  return <SvgXml xml={xml} override={props} />;
}`

if the svg is invalid  it wonot go to onError function as the uri is a valid url and the data will be undefined and it will set xml as undefined ,

`export function SvgXml(props: XmlProps) {
  const { onError = err, xml, override } = props;
  const ast = useMemo<JsxAST | null>(
    () => (xml !== null? parse(xml) : null),
    [xml],
  );

  try {
    return <SvgAst ast={ast} override={override || props} />;
  } catch (error) {
    onError(error);
    return null;
  }
}`

and in this usememo it will go the parse function and it will cause the error as the source will be undefined too.
 I suggest we replace usememo with this code to handle undefined data (invalid svg) too 

  const ast = useMemo<JsxAST | null>(
    () => (![null , undefined].includes(xml) ? parse(xml) : null),
    [xml],
  );

**Comment by TwistedMinda** [comment] 2023-06-12 11:00
I simply added a patch:

```
diff --git a/node_modules/react-native-svg/src/xml.tsx b/node_modules/react-native-svg/src/xml.tsx
index ff9b02e..613010b 100644
--- a/node_modules/react-native-svg/src/xml.tsx
+++ b/node_modules/react-native-svg/src/xml.tsx
@@ -108,7 +108,13 @@ export const err = console.error.bind(console);
 export function SvgXml(props: XmlProps) {
   const { onError = err, xml, override } = props;
   const ast = useMemo<JsxAST | null>(
-    () => (xml !== null ? parse(xml) : null),
+    () => {
+      try {
+        return (xml !== null ? parse(xml) : null)
+      } catch (err) {
+        return null
+      }
+    },
     [xml],
   );
 

```
